# Generated by Django 5.0.3 on 2024-04-20 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_sharewishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharewishlist',
            name='wishlist_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
