# Generated by Django 5.0.2 on 2024-04-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_status'),
    ]

    operations = [
    ]
